In [1]:
import torch

In [ ]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
#get tensor as python int
print(scalar.item())

vector = torch.tensor(([3 , 4, 5]))
print(vector.ndim)

7
1


In [ ]:
MATRIX  = torch.tensor([
    [2 , 3 ],
    [3 , 4],
    [9 , 6]

])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([3, 2])


In [ ]:
TENSOR = torch.tensor(
    [
        [
            [2 ,1],
            [0 ,1],
            [0 ,1]

         ],

          [
            [2 ,1],
            [0 ,1],
            [0 ,1]

         ],
          [
            [2 ,1],
            [0 ,1],
            [0 ,1]

         ]


     ]

)
print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([3, 3, 2])
3


### RANDOM TENSORS

##### TIME STAMP 1:45.28

In [ ]:
random_tensor = torch.rand( 100, 100, 3)
print(random_tensor.shape)

torch.Size([100, 100, 3])


import matplotlib.pyplot as plt

plt.figure()

plt.imshow(random_tensor)

plt.show()

#### TIME 1:46:46
#### ZEROS AND ONES

In [ ]:
### recap of matrix multiplication

zeros = torch.zeros(size = ( 3 , 4) )
ones = torch.ones(size = (4 , 3))
print(zeros.shape , ones.shape)
results2 = torch.mm(zeros , ones)
print(results2)

torch.Size([3, 4]) torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Range tensors

torch.arange(1, 10)

In [ ]:
#rgb
start = 200
end = 255
step = abs((start- end)//3)
print(step)

r = torch.arange(start = start , end = end , step = step)
g = torch.arange(start = start , end = end , step = step)
b = torch.arange(start = start , end = end , step = step)

19


## tensors like

In [ ]:
r_like = torch.zeros_like(input= r)
g_like = torch.ones_like(input= g)
b_like = torch.ones_like(input= b)

In [ ]:
r_like , g_like

(tensor([0, 0, 0]), tensor([1, 1, 1]))

### Tensor dtypes

**Note**
device = cpu ,cuda

source : https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

In [ ]:


ten_16 = torch.tensor(data = list(r_like) , dtype = torch.float16 , device =  None , requires_grad = False)
ten_32 = ten_16.type(torch.float32)
ten_64 = ten_16.type(torch.float64)
ten_64_cuda = ten_64.to('cpu')
print(ten_64.get_device())


-1


#### Tensor manipulation

Operation:

* Addition

* subtraction

* Element wise multiplication

* Matrix multiplication

In [ ]:
### ADDING
tensor_1 = torch.tensor([1 , 2 , 3])
tensor_2 = torch.tensor([4 , 5 , 6])

print(tensor_1 + 10)
tensor_1 + tensor_2


tensor([5, 7, 9])

In [ ]:
### subtraction
tensor_1 - tensor_2

tensor([-3, -3, -3])

In [ ]:
### multiplication elemnt wise
tensor_1 * tensor_2

tensor([ 4, 10, 18])

### Matrix multiplication//Dot procuct

In [ ]:
  tensor_1 , tensor_2

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [ ]:
%%time
final_tensor = torch.zeros_like(tensor_1)
for i in range(len(list(tensor_1))):
  num_1 , num_2 = tensor_1[i] , tensor_2[i]
  final_tensor[i] = num_1 * num_2

print(f" {final_tensor} {sum(final_tensor)}")





 tensor([ 4, 10, 18]) 32
CPU times: user 939 µs, sys: 802 µs, total: 1.74 ms
Wall time: 1.69 ms


In [ ]:
%%time
print(torch.matmul(tensor_1 , tensor_2))

tensor(32)
CPU times: user 1.02 ms, sys: 2 µs, total: 1.03 ms
Wall time: 1.03 ms


### steps for matrix mmultiplication

* Take the row for the matrix being multiplied
* Multipli each element in the row to each
* column  value in matrix 1
* find the sum and assing it the the n cordinate * index of the result matrix  


In [ ]:
tensor_1 , tensor_2 = torch.rand(3 , 2) , torch.rand(3 , 2)
result_matrix = tensor_1.shape[-1] , tensor_2.shape[-1]

if tensor_1.shape[-1] != tensor_2.shape[0]:
  print("Transposed the tensor")
  res = torch.matmul(tensor_1 , tensor_2.T)
else:
  res = torch.matmul(tensor_1 , tensor_2)

print(f"Result is {res} , {res.shape}")

Transposed the tensor
Result is tensor([[0.3889, 0.3608, 0.2964],
        [0.0915, 0.0833, 0.0661],
        [0.6541, 0.5234, 0.2974]]) , torch.Size([3, 3])


### max , min , sum , mean , etc(tensor aggregation)

In [ ]:
x = torch.arange(1 , 11 , 1)

## max
print(x.max())

## min
print(x.min())

## mean
print(x.type(torch.float32).mean())

## sum

print(x.sum())

tensor(10)
tensor(1)
tensor(5.5000)
tensor(55)


In [ ]:
x = torch.rand(10)
## finding positional mean and max
print(f"Min num index {x.argmin()}")

##finding the max number index
print(f"Mux num index {x.argmax()}")

Min num index 0
Mux num index 1


## reshaping ,stacking and squeezing  and unsqueezing

In [ ]:
x = torch.arange(1 , 10 , 1)


In [ ]:
### reshape
print(x , x.shape)
x_reshaped = x.reshape(9 , 1)
x_reshaped

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
### view
##view of a tebsor shares the same memory of a tensor
z = x.view(3 , 3)
z[2,-1] = 1
x


tensor([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [ ]:
## stacking
x = x.reshape(3 , 3)
x_stacked = torch.stack([x , x] , dim=0)

print(f"Originaal x {x}\n")
print(f"stacked x {x_stacked}\n")
print(f"Differnt shapes x-shape {x.shape}\nX-stacked shape {x_stacked.shape}")

Originaal x tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 1]])

stacked x tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 1]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 1]]])

Differnt shapes x-shape torch.Size([3, 3])
X-stacked shape torch.Size([2, 3, 3])


In [ ]:
## squeeze and unsqueeze
y = torch.arange(1 , 19 , 1)
y = y.reshape(3 , 1 ,3 ,2)
print("Original y" , y , "\n")
y_squeezed = torch.squeeze(y )
print(y.shape ,y_squeezed , y_squeezed.shape)

## unsqueeze
print("\nUnsqueezing")
y_unsqueezed = torch.unsqueeze(y_squeezed , 1 )
print(y_unsqueezed , y_unsqueezed.shape)

Original y tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]]],


        [[[ 7,  8],
          [ 9, 10],
          [11, 12]]],


        [[[13, 14],
          [15, 16],
          [17, 18]]]]) 

torch.Size([3, 1, 3, 2]) tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]]) torch.Size([3, 3, 2])

Unsqueezing
tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]]],


        [[[ 7,  8],
          [ 9, 10],
          [11, 12]]],


        [[[13, 14],
          [15, 16],
          [17, 18]]]]) torch.Size([3, 1, 3, 2])


In [ ]:
## permute
## returns a view ie  share the memory
"[3, 1, 3, 2]"
y_2 = y_unsqueezed

y_permute = y_2.permute(1 , -2 , 0 , -1)
print(y_permute , y_permute.shape)


tensor([[[[ 1,  2],
          [ 7,  8],
          [13, 14]],

         [[ 3,  4],
          [ 9, 10],
          [15, 16]],

         [[ 5,  6],
          [11, 12],
          [17, 18]]]]) torch.Size([1, 3, 3, 2])


In [ ]:
y_2.shape , y_permute.shape

(torch.Size([3, 1, 3, 2]), torch.Size([1, 3, 3, 2]))

In [ ]:
#### Indexing

In [1]:
import torch

In [5]:
x = torch.arange(1 , 61 , 1)
x = x.reshape(5 , 4, 3)
print(x)
print("\n" , x.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]],

        [[25, 26, 27],
         [28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45],
         [46, 47, 48]],

        [[49, 50, 51],
         [52, 53, 54],
         [55, 56, 57],
         [58, 59, 60]]])

 torch.Size([5, 4, 3])


In [11]:
[51 , 54] == list(x[4,0:2,-1])

True

In [10]:
print(x[0:2,0:2,-1])

tensor([51, 54])


### pythorch tensors and numpy

* numpy -> torch

`torch.from_numpy(ndarray)`

* torch -> numpy

`torch.Tensor.numpy() `

* make sure to track the dtype ,

* the new tennsor is created in diffrent memory


In [12]:
import numpy as np


In [24]:
### make sure to track the dtype , the new tennsor is created in diffrent memory
array = np.arange(1 , 11 , 1)
tensor_1 = torch.from_numpy(array)
new_array = array.reshape(2 , 5)
new_array = new_array.astype(np.float32) ## changing the dytpe of the numpy
tensor_2 = torch.from_numpy(new_array)

tensor_2.dtype , new_array.dtype

(torch.float32, dtype('float32'))

In [30]:
numpy_array = (x.type(torch.float64)).numpy()
numpy_array.dtype

dtype('float64')

#### Reproducbility (trying to take random out of random)

To reduce randomness we use the concept of random seed as there is no true randomness in cs

In [31]:
seed = 24

## set the seed
## for each instace initiated set the random seed
torch.manual_seed(seed)
random_tensor_1 = torch.rand(3 , 3)
torch.manual_seed(seed)
random_tensor_2 = torch.rand(3 , 3)

print(random_tensor_1 == random_tensor_2)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### ***Using gpu***

In [2]:
!nvidia-smi

Tue Feb 13 18:26:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              11W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
## check for gpu access

import torch
print(torch.cuda.is_available())

True


In [3]:
## set up Device agnostic true
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
## count gpu
torch.cuda.device_count()

1

## putting tensors and models on gpu

In [7]:
tensor = torch.tensor([1 , 3 , 5, 6])

In [11]:
print(tensor.device)
tensor= tensor.to(device)
print(tensor.device)

cpu
cuda:0


#### Numpy and gpu
for convertiing tensors to numpy on gpu you have to change the tensor to cpu device and trhen convert it later


In [15]:
numpy_tensor = tensor.cpu().numpy()
numpy_tensor


array([1, 3, 5, 6])